In [5]:
from data_sources import *
import akshare as ak

code = '002104'

In [5]:
res = get_profile_ef(code)
res

2025-08-22 22:47:38 | INFO     | datasource.efinance | ok rows=1 cols=12 elapsed=71.2ms args=('002104',) kwargs={}

,股票代码,股票名称,净利润,总市值,流通市值,所处行业,市盈率(动),市净率,ROE,毛利率,净利率,板块编号
0,002104,恒宝股份,23935679.95,20435036442.900002,17300768115.400002,通信设备,213.44,9.64,1.11,29.312155,9.665555,BK0448

In [2]:
res2 = get_profile_em(code)
res2

2025-08-22 22:12:02 | INFO     | datasource.efinance | get_profile_em ok rows=9 cols=2 elapsed=112.9ms args=('002104',) kwargs={}

   item               value
0   总市值  20435036442.900002
1  流通市值  17300768115.400002
2    行业                通信设备
3  上市时间            20070110
4    最新               28.85
5  股票代码              002104
6  股票简称                恒宝股份
7   总股本         708320154.0
8   流通股         599680004.0

In [4]:
res3 = get_profile_xq(code)
res3

SZ002104
2025-08-22 23:06:51 | INFO     | datasource.efinance | ok rows=39 cols=2 elapsed=137.0ms args=('002104',) kwargs={}

,item,value
0,actual_controller,钱京 (18.95%)
1,actual_issue_vol,28800000.0
2,actual_rc_net_amt,223796900.0
3,affiliate_industry,"{'ind_code': 'BK0029', 'ind_name': '通信设备'}"
4,chairman,钱京
5,classi_name,民营企业
6,currency,CNY
7,currency_encode,019001
8,district_encode,321181
9,email,ir@hengbao.com
10,established_date,843494400000
11,executives_nums,13
12,fax,86-511-86644324
13,general_manager,钱京
14,issue_price,8.43
15,legal_representative,钱京
16,listed_date,1168358400000
17,main_operation_business,高端智能化产品及数字安全解决方案等服务。
18,office_address_cn,江苏省镇江市丹阳市横塘工业区
19,office_address_en,None
20,online_success_rate_of_issue,0.6775
21,operating_scope,智能卡、磁条卡、票证、票据、密码信封、智能标签、智能终端、商用密码产品及相关系统软件、读...
22,org_cn_introduction,恒宝股份有限公司的主营业务是高端智能化产品及数字安全解决方案等服务。公司的主要产品是票证类、...
23,org_id,03132338
24,org_name_cn,恒宝股份有限公司
25,org_name_en,"Hengbao Co.,Ltd."
26,org_short_name_cn,恒宝股份
27,org_short_name_en,"Hengbao Co.,LTD."
28,org_website,www.hengbao.com
29,pe_after_issuing,24.79
30,postcode,212355
31,pre_name_cn,江苏恒宝股份有限公司
32,provincial_name,江苏省
33,reg_address_cn,江苏省镇江市丹阳市横塘工业区
34,reg_address_en,None
35,reg_asset,708320154.0
36,secretary,王坚
37,staff_num,1025
38,telephone,86-511-86644324